
const q=id=>document.getElementById(id), n=id=>parseFloat(q(id).value)||0;
const set=(id,v,d=3)=>q(id).textContent=Number.isFinite(v)?v.toFixed(d):"—";
const circle=d=>0.0000007853981634*d*d;
function save(){const d={};document.querySelectorAll("input,select").forEach(e=>d[e.id]=e.value);localStorage.setItem("rigcalc-v1",JSON.stringify(d))}
function load(){try{const d=JSON.parse(localStorage.getItem("rigcalc-v1")||"{}");Object.entries(d).forEach(([k,v])=>{if(q(k))q(k).value=v})}catch(e){}}
function calcCap(){const h=n("cap_hole"),od=n("cap_od"),id=n("cap_id"),l=n("cap_len"),hc=circle(h),ac=circle(h)-circle(od),pc=circle(id);set("r_hole_cap",hc,6);set("r_hole_vol",hc*l,3);set("r_ann_cap",ac,6);set("r_ann_vol",ac*l,3);set("r_pipe_cap",pc,6);set("r_pipe_vol",pc*l,3);set("r_closed_disp",circle(od),6);set("r_steel_disp",circle(od)-circle(id),6)}
function calcPump(){const li=n("pump_liner"),st=n("pump_stroke"),ef=n("pump_eff")/100,spm=n("pump_spm"),ct=n("pump_count"),av=n("pump_annvol"),ac=n("pump_anncap"),th=3*0.0000000007853981634*li*li*st,ad=th*ef,co=ad*ct,fl=co*spm;set("r_pump_theor",th,6);set("r_pump_adj",ad,6);set("r_pump_flow",fl,3);set("r_bu_strokes",co?av/co:0,0);set("r_bu_time",fl?av/fl:0,2);set("r_stk_m",co?ac/co:0,2)}
function calcWC(){const r=n("wc_density"),t=n("wc_tvd"),s=n("wc_sidpp"),m=n("wc_margin"),p=n("wc_surface"),hy=r*9.80665*t/1000,inc=t?(s+m)*1000/(9.80665*t):0,k=r+inc,eq=t?r+p*1000/(9.80665*t):0;set("r_wc_hydro",hy/1000,3);set("r_wc_inc",inc,1);set("r_wc_kmd",k,1);set("r_wc_sg",k/1000,3);set("r_wc_eqd",eq,1)}
function calcCem(){const h=n("cem_hole"),od=n("cem_od"),l=n("cem_len"),ex=n("cem_excess")/100,ly=n("cem_lead_yield"),tv=n("cem_tail_vol"),ty=n("cem_tail_yield"),cap=circle(h)-circle(od),base=cap*l,total=base*(1+ex),tail=Math.min(tv,total),lead=Math.max(total-tail,0),s=(ly?lead*1000/ly:0)+(ty?tail*1000/ty:0);set("r_cem_cap",cap,6);set("r_cem_base",base,3);set("r_cem_total",total,3);set("r_cem_lead",lead,3);set("r_cem_tail",tail,3);set("r_cem_sacks",s,1)}
function calcTrip(){const od=n("trip_od"),id=n("trip_id"),sl=n("trip_stand"),st=n("trip_stands"),mode=q("trip_mode").value,start=n("trip_start"),obs=n("trip_obs"),len=sl*st,disp=mode==="Wet"?circle(od):circle(od)-circle(id),fill=len*disp,exp=start-fill,chg=start-obs,diff=chg-fill;set("r_trip_len",len,2);set("r_trip_disp",disp,6);set("r_trip_fill",fill,3);set("r_trip_expected",exp,3);set("r_trip_change",chg,3);set("r_trip_diff",diff,3);const b=q("trip_status_box");b.classList.toggle("status-bad",Math.abs(diff)>.25);b.classList.toggle("status-good",Math.abs(diff)<=.25)}
function stat(box,text,v,min,max){let t="Within window",g=true;if(v<min){t="Below minimum";g=false}if(v>max){t="Above maximum";g=false}q(text).textContent=t;q(box).classList.toggle("status-good",g);q(box).classList.toggle("status-bad",!g)}
function calcMPD(){const r=n("mpd_density"),t=n("mpd_tvd"),sb=n("mpd_sbp"),af=n("mpd_afp"),tar=n("mpd_target"),pp=n("mpd_ppg"),fg=n("mpd_fg"),lm=n("mpd_lowmargin"),hm=n("mpd_highmargin"),hy=r*9.80665*t/1000,st=hy+sb,ci=hy+sb+af,min=pp*t+lm,max=fg*t-hm,win=Math.max(max-min,0),es=t?st*1000/(9.80665*t):0,ec=t?ci*1000/(9.80665*t):0;set("r_mpd_hydro",hy/1000,3);set("r_mpd_static",st/1000,3);set("r_mpd_circ",ci/1000,3);set("r_mpd_esd",es,1);set("r_mpd_ecd",ec,1);set("r_mpd_req_static",Math.max(tar-hy,0),0);set("r_mpd_req_circ",Math.max(tar-hy-af,0),0);set("r_mpd_window",win,0);stat("mpd_static_status_box","r_mpd_static_status",st,min,max);stat("mpd_circ_status_box","r_mpd_circ_status",ci,min,max);q("windowMin").textContent=(min/1000).toFixed(2)+" MPa";q("windowMax").textContent=(max/1000).toFixed(2)+" MPa";const pct=max>min?Math.max(0,Math.min(100,(ci-min)/(max-min)*100)):50;q("windowMarker").style.bottom=`calc(${pct}% - 12px)`;q("windowMarker").textContent=(ci/1000).toFixed(2)+" MPa"}
function all(){calcCap();calcPump();calcWC();calcCem();calcTrip();calcMPD();save()}
document.querySelectorAll("input,select").forEach(e=>e.addEventListener("input",all));
document.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));q(b.dataset.open).classList.add("active");scrollTo(0,0)}));
document.querySelectorAll(".back").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));q("dashboard").classList.add("active");scrollTo(0,0)}));
q("installHelpBtn").onclick=()=>q("installModal").classList.remove("hidden");q("closeModal").onclick=()=>q("installModal").classList.add("hidden");
q("themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("rigcalc-theme",document.body.classList.contains("dark")?"dark":"light")};
if(localStorage.getItem("rigcalc-theme")==="dark")document.body.classList.add("dark");
load();all();
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
